# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCollege.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCollegeDialog(object):
    def setupUi(self, AddCollegeDialog):
        AddCollegeDialog.setObjectName("AddCollegeDialog")
        AddCollegeDialog.resize(450, 400)
        AddCollegeDialog.setMinimumSize(QtCore.QSize(450, 400))
        AddCollegeDialog.setMaximumSize(QtCore.QSize(450, 400))
        self.label = QtWidgets.QLabel(AddCollegeDialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddCollegeDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddCollegeDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.collegeCodeEdit = QtWidgets.QLineEdit(AddCollegeDialog)
        self.collegeCodeEdit.setGeometry(QtCore.QRect(20, 140, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.collegeCodeEdit.setFont(font)
        self.collegeCodeEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.collegeCodeEdit.setObjectName("collegeCodeEdit")
        self.collegeNameEdit = QtWidgets.QLineEdit(AddCollegeDialog)
        self.collegeNameEdit.setGeometry(QtCore.QRect(20, 230, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.collegeNameEdit.setFont(font)
        self.collegeNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.collegeNameEdit.setObjectName("collegeNameEdit")
        self.pushButton = QtWidgets.QPushButton(AddCollegeDialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 320, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #43A047;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #388E3C;\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(AddCollegeDialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(AddCollegeDialog)
        QtCore.QMetaObject.connectSlotsByName(AddCollegeDialog)

    def retranslateUi(self, AddCollegeDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCollegeDialog.setWindowTitle(_translate("AddCollegeDialog", "Add College"))
        self.label.setText(_translate("AddCollegeDialog", "CREATE A NEW COLLEGE ENTRY"))
        self.label_2.setText(_translate("AddCollegeDialog", "College code"))
        self.label_3.setText(_translate("AddCollegeDialog", "College name"))
        self.collegeCodeEdit.setPlaceholderText(_translate("AddCollegeDialog", "ex. CCS"))
        self.collegeNameEdit.setPlaceholderText(_translate("AddCollegeDialog", "ex. College Of Computer Studies"))
        self.pushButton.setText(_translate("AddCollegeDialog", "ADD COLLEGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddCollegeDialog = QtWidgets.QDialog()
    ui = Ui_AddCollegeDialog()
    ui.setupUi(AddCollegeDialog)
    AddCollegeDialog.show()
    sys.exit(app.exec_())
