# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProgramDialog(object):
    def setupUi(self, AddProgramDialog):
        AddProgramDialog.setObjectName("AddProgramDialog")
        AddProgramDialog.resize(450, 492)
        AddProgramDialog.setMinimumSize(QtCore.QSize(450, 492))
        AddProgramDialog.setMaximumSize(QtCore.QSize(450, 492))
        self.label = QtWidgets.QLabel(AddProgramDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddProgramDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddProgramDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddProgramDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.programCodeEdit = QtWidgets.QLineEdit(AddProgramDialog)
        self.programCodeEdit.setGeometry(QtCore.QRect(20, 140, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.programCodeEdit.setFont(font)
        self.programCodeEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.programCodeEdit.setObjectName("programCodeEdit")
        self.programNameEdit = QtWidgets.QLineEdit(AddProgramDialog)
        self.programNameEdit.setGeometry(QtCore.QRect(20, 230, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.programNameEdit.setFont(font)
        self.programNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.programNameEdit.setObjectName("programNameEdit")
        self.pushButton = QtWidgets.QPushButton(AddProgramDialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 410, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #43A047;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #388E3C;\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.collegeCodeBox = QtWidgets.QComboBox(AddProgramDialog)
        self.collegeCodeBox.setGeometry(QtCore.QRect(20, 320, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.collegeCodeBox.setFont(font)
        self.collegeCodeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.collegeCodeBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.collegeCodeBox.setObjectName("collegeCodeBox")
        self.line = QtWidgets.QFrame(AddProgramDialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(AddProgramDialog)
        QtCore.QMetaObject.connectSlotsByName(AddProgramDialog)

    def retranslateUi(self, AddProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        AddProgramDialog.setWindowTitle(_translate("AddProgramDialog", "Add Program"))
        self.label.setText(_translate("AddProgramDialog", "CREATE A NEW PROGRAM ENTRY"))
        self.label_2.setText(_translate("AddProgramDialog", "Program code"))
        self.label_3.setText(_translate("AddProgramDialog", "Program name"))
        self.label_4.setText(_translate("AddProgramDialog", "College code"))
        self.programCodeEdit.setPlaceholderText(_translate("AddProgramDialog", "ex. BSCS"))
        self.programNameEdit.setPlaceholderText(_translate("AddProgramDialog", "ex. Bachelor Of Science In Computer Science"))
        self.pushButton.setText(_translate("AddProgramDialog", "ADD PROGRAM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddProgramDialog = QtWidgets.QDialog()
    ui = Ui_AddProgramDialog()
    ui.setupUi(AddProgramDialog)
    AddProgramDialog.show()
    sys.exit(app.exec_())
