# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddStudentDialog(object):
    def setupUi(self, AddStudentDialog):
        AddStudentDialog.setObjectName("AddStudentDialog")
        AddStudentDialog.resize(450, 580)
        AddStudentDialog.setMinimumSize(QtCore.QSize(450, 580))
        AddStudentDialog.setMaximumSize(QtCore.QSize(450, 580))
        self.label = QtWidgets.QLabel(AddStudentDialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddStudentDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddStudentDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(AddStudentDialog)
        self.label_5.setGeometry(QtCore.QRect(30, 370, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AddStudentDialog)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(AddStudentDialog)
        self.label_7.setGeometry(QtCore.QRect(240, 370, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(AddStudentDialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 500, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #43A047;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #388E3C;\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.firstNameEdit = QtWidgets.QLineEdit(AddStudentDialog)
        self.firstNameEdit.setGeometry(QtCore.QRect(20, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.firstNameEdit.setFont(font)
        self.firstNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.idNumberEdit = QtWidgets.QLineEdit(AddStudentDialog)
        self.idNumberEdit.setGeometry(QtCore.QRect(20, 140, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.idNumberEdit.setFont(font)
        self.idNumberEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.idNumberEdit.setObjectName("idNumberEdit")
        self.lastNameEdit = QtWidgets.QLineEdit(AddStudentDialog)
        self.lastNameEdit.setGeometry(QtCore.QRect(230, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.lastNameEdit.setFont(font)
        self.lastNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.yearLevelBox = QtWidgets.QComboBox(AddStudentDialog)
        self.yearLevelBox.setGeometry(QtCore.QRect(20, 410, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.yearLevelBox.setFont(font)
        self.yearLevelBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yearLevelBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yearLevelBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.yearLevelBox.setObjectName("yearLevelBox")
        self.yearLevelBox.addItem("")
        self.yearLevelBox.addItem("")
        self.yearLevelBox.addItem("")
        self.yearLevelBox.addItem("")
        self.genderBox = QtWidgets.QComboBox(AddStudentDialog)
        self.genderBox.setGeometry(QtCore.QRect(20, 320, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.genderBox.setFont(font)
        self.genderBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.genderBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.genderBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.genderBox.setObjectName("genderBox")
        self.genderBox.addItem("")
        self.genderBox.addItem("")
        self.programCodeBox = QtWidgets.QComboBox(AddStudentDialog)
        self.programCodeBox.setGeometry(QtCore.QRect(230, 410, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.programCodeBox.setFont(font)
        self.programCodeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.programCodeBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.programCodeBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.programCodeBox.setObjectName("programCodeBox")
        self.line = QtWidgets.QFrame(AddStudentDialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 451, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(AddStudentDialog)
        self.yearLevelBox.setCurrentIndex(-1)
        self.genderBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AddStudentDialog)

    def retranslateUi(self, AddStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        AddStudentDialog.setWindowTitle(_translate("AddStudentDialog", "Add Student"))
        self.label.setText(_translate("AddStudentDialog", "CREATE A NEW STUDENT ENTRY"))
        self.label_2.setText(_translate("AddStudentDialog", "ID Number"))
        self.label_3.setText(_translate("AddStudentDialog", "Name"))
        self.label_5.setText(_translate("AddStudentDialog", "Year level"))
        self.label_6.setText(_translate("AddStudentDialog", "Gender"))
        self.label_7.setText(_translate("AddStudentDialog", "Program code"))
        self.pushButton.setText(_translate("AddStudentDialog", "ADD STUDENT"))
        self.firstNameEdit.setPlaceholderText(_translate("AddStudentDialog", "First Name"))
        self.idNumberEdit.setPlaceholderText(_translate("AddStudentDialog", "ex. 2025-0001"))
        self.lastNameEdit.setPlaceholderText(_translate("AddStudentDialog", "Last Name"))
        self.yearLevelBox.setItemText(0, _translate("AddStudentDialog", "1"))
        self.yearLevelBox.setItemText(1, _translate("AddStudentDialog", "2"))
        self.yearLevelBox.setItemText(2, _translate("AddStudentDialog", "3"))
        self.yearLevelBox.setItemText(3, _translate("AddStudentDialog", "4"))
        self.genderBox.setItemText(0, _translate("AddStudentDialog", "M"))
        self.genderBox.setItemText(1, _translate("AddStudentDialog", "F"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddStudentDialog = QtWidgets.QDialog()
    ui = Ui_AddStudentDialog()
    ui.setupUi(AddStudentDialog)
    AddStudentDialog.show()
    sys.exit(app.exec_())
