# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateStudentDialog(object):
    def setupUi(self, UpdateStudentDialog):
        UpdateStudentDialog.setObjectName("UpdateStudentDialog")
        UpdateStudentDialog.resize(450, 580)
        UpdateStudentDialog.setMinimumSize(QtCore.QSize(450, 580))
        UpdateStudentDialog.setMaximumSize(QtCore.QSize(450, 580))
        self.label = QtWidgets.QLabel(UpdateStudentDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(UpdateStudentDialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 451, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(UpdateStudentDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.idNumberEdit = QtWidgets.QLineEdit(UpdateStudentDialog)
        self.idNumberEdit.setGeometry(QtCore.QRect(20, 140, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.idNumberEdit.setFont(font)
        self.idNumberEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.idNumberEdit.setReadOnly(True)
        self.idNumberEdit.setObjectName("idNumberEdit")
        self.label_3 = QtWidgets.QLabel(UpdateStudentDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.firstNameEdit = QtWidgets.QLineEdit(UpdateStudentDialog)
        self.firstNameEdit.setGeometry(QtCore.QRect(20, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.firstNameEdit.setFont(font)
        self.firstNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.firstNameEdit.setReadOnly(False)
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.lastNameEdit = QtWidgets.QLineEdit(UpdateStudentDialog)
        self.lastNameEdit.setGeometry(QtCore.QRect(230, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.lastNameEdit.setFont(font)
        self.lastNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.lastNameEdit.setReadOnly(False)
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.label_4 = QtWidgets.QLabel(UpdateStudentDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 370, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(UpdateStudentDialog)
        self.label_5.setGeometry(QtCore.QRect(240, 370, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.yearLevelBox = QtWidgets.QComboBox(UpdateStudentDialog)
        self.yearLevelBox.setGeometry(QtCore.QRect(20, 410, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.yearLevelBox.setFont(font)
        self.yearLevelBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yearLevelBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.yearLevelBox.setObjectName("yearLevelBox")
        self.yearLevelBox.addItem("")
        self.yearLevelBox.addItem("")
        self.yearLevelBox.addItem("")
        self.yearLevelBox.addItem("")
        self.programCodeBox = QtWidgets.QComboBox(UpdateStudentDialog)
        self.programCodeBox.setGeometry(QtCore.QRect(230, 410, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.programCodeBox.setFont(font)
        self.programCodeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.programCodeBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.programCodeBox.setObjectName("programCodeBox")
        self.label_6 = QtWidgets.QLabel(UpdateStudentDialog)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(UpdateStudentDialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 500, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #43A047;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #388E3C;\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.genderBox = QtWidgets.QComboBox(UpdateStudentDialog)
        self.genderBox.setGeometry(QtCore.QRect(20, 320, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.genderBox.setFont(font)
        self.genderBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.genderBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.genderBox.setObjectName("genderBox")
        self.genderBox.addItem("")
        self.genderBox.addItem("")

        self.retranslateUi(UpdateStudentDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateStudentDialog)

    def retranslateUi(self, UpdateStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateStudentDialog.setWindowTitle(_translate("UpdateStudentDialog", "Update Student"))
        self.label.setText(_translate("UpdateStudentDialog", "UPDATE STUDENT INFORMATION"))
        self.label_2.setText(_translate("UpdateStudentDialog", "ID Number"))
        self.label_3.setText(_translate("UpdateStudentDialog", "Name"))
        self.firstNameEdit.setPlaceholderText(_translate("UpdateStudentDialog", "First Name"))
        self.lastNameEdit.setPlaceholderText(_translate("UpdateStudentDialog", "Last Name"))
        self.label_4.setText(_translate("UpdateStudentDialog", "Year level"))
        self.label_5.setText(_translate("UpdateStudentDialog", "Program code"))
        self.yearLevelBox.setItemText(0, _translate("UpdateStudentDialog", "1"))
        self.yearLevelBox.setItemText(1, _translate("UpdateStudentDialog", "2"))
        self.yearLevelBox.setItemText(2, _translate("UpdateStudentDialog", "3"))
        self.yearLevelBox.setItemText(3, _translate("UpdateStudentDialog", "4"))
        self.label_6.setText(_translate("UpdateStudentDialog", "Gender"))
        self.pushButton.setText(_translate("UpdateStudentDialog", "UPDATE STUDENT"))
        self.genderBox.setItemText(0, _translate("UpdateStudentDialog", "M"))
        self.genderBox.setItemText(1, _translate("UpdateStudentDialog", "F"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateStudentDialog = QtWidgets.QDialog()
    ui = Ui_UpdateStudentDialog()
    ui.setupUi(UpdateStudentDialog)
    UpdateStudentDialog.show()
    sys.exit(app.exec_())
