# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateProgramDialog(object):
    def setupUi(self, UpdateProgramDialog):
        UpdateProgramDialog.setObjectName("UpdateProgramDialog")
        UpdateProgramDialog.resize(450, 492)
        UpdateProgramDialog.setMinimumSize(QtCore.QSize(450, 492))
        UpdateProgramDialog.setMaximumSize(QtCore.QSize(450, 492))
        self.label = QtWidgets.QLabel(UpdateProgramDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(UpdateProgramDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(UpdateProgramDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(UpdateProgramDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.programCodeEdit = QtWidgets.QLineEdit(UpdateProgramDialog)
        self.programCodeEdit.setGeometry(QtCore.QRect(20, 140, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.programCodeEdit.setFont(font)
        self.programCodeEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.programCodeEdit.setObjectName("programCodeEdit")
        self.programNameEdit = QtWidgets.QLineEdit(UpdateProgramDialog)
        self.programNameEdit.setGeometry(QtCore.QRect(20, 230, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.programNameEdit.setFont(font)
        self.programNameEdit.setStyleSheet("QLineEdit {\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }")
        self.programNameEdit.setObjectName("programNameEdit")
        self.collegeCodeBox = QtWidgets.QComboBox(UpdateProgramDialog)
        self.collegeCodeBox.setGeometry(QtCore.QRect(20, 320, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.collegeCodeBox.setFont(font)
        self.collegeCodeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.collegeCodeBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.collegeCodeBox.setStyleSheet("QComboBox {\n"
"        padding: 6px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        color: black\n"
"    }\n"
"    QComboBox QAbstractItemView {\n"
"        border: 1px solid #ccc;\n"
"        selection-background-color: #2196F3;\n"
"        selection-color: #ffffff;\n"
"        background-color: #ffffff;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"    }")
        self.collegeCodeBox.setObjectName("collegeCodeBox")
        self.confirmButton = QtWidgets.QPushButton(UpdateProgramDialog)
        self.confirmButton.setGeometry(QtCore.QRect(100, 410, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmButton.setStyleSheet("QPushButton {\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #43A047;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #388E3C;\n"
"    }")
        self.confirmButton.setObjectName("confirmButton")
        self.line = QtWidgets.QFrame(UpdateProgramDialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(UpdateProgramDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateProgramDialog)

    def retranslateUi(self, UpdateProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateProgramDialog.setWindowTitle(_translate("UpdateProgramDialog", "Update Program"))
        self.label.setText(_translate("UpdateProgramDialog", "UPDATE PROGRAM INFORMATION"))
        self.label_2.setText(_translate("UpdateProgramDialog", "Program code"))
        self.label_3.setText(_translate("UpdateProgramDialog", "Program name"))
        self.label_4.setText(_translate("UpdateProgramDialog", "College code"))
        self.programCodeEdit.setPlaceholderText(_translate("UpdateProgramDialog", "ex. BSCS"))
        self.programNameEdit.setPlaceholderText(_translate("UpdateProgramDialog", "ex. Bachelor Of Science In Computer Science"))
        self.confirmButton.setText(_translate("UpdateProgramDialog", "UPDATE PROGRAM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateProgramDialog = QtWidgets.QDialog()
    ui = Ui_UpdateProgramDialog()
    ui.setupUi(UpdateProgramDialog)
    UpdateProgramDialog.show()
    sys.exit(app.exec_())
